// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://faduyqgtdoalzkpxwhuz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZhZHV5cWd0ZG9hbHprcHh3aHV6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3MDgyNjYsImV4cCI6MjA2OTI4NDI2Nn0.qTY4JrPH7uP_2y386Yg1dtAojmh8PE-JbHywlnr_LFg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});